### ISSUE TITLE
Facing some issue while adding a web part

### ISSUE THREAD

**Issue by Soumyawrk** [waldekmastykarz/spfx-weather-webpart#1]
![whtr issue](https://cloud.githubusercontent.com/assets/25977928/23256504/c158e48e-f9e5-11e6-9cd7-4cf8df341fe2.PNG)

**Comment by waldekmastykarz** [comment]
Are you adding the web part in the hosted version of the workbench?

**Comment by Soumyawrk** [comment]
Am getting the issue in both local workbench as well as hosted version of the work bench..

**Comment by waldekmastykarz** [comment]
In your example I'm seeing a different name, than the name used in my sample (WhetrWebpartWebPart). Are you trying to rebuild this web part using a newer build of SPFx?

**Comment by Soumyawrk** [comment]
Yes am trying to create a new project..

**Comment by waldekmastykarz** [comment]
This code sample is built using an older version of the SharePoint Framework, which is why you can't use the code as-is. You would have to adopt it to match the version of the SharePoint Framework that you are using.

**Comment by Soumyawrk** [comment]
I adopted few parts from your repository , but am getting the same issue when ever i am trying to add an external plug in.

**Comment by waldekmastykarz** [comment]
In SharePoint Framework RC0 there was a known issue when loading jQuery and jQuery plugins declaratively didn't work. Could you confirm that it's not the same bug by temporarily removing any references to the simpleWeather script and checking if you still have this error?

**Comment by Soumyawrk** [comment]
Yes once I remove all the references my web part is not having a single issue and is being deployed smoothly. Once i load references its returning me with errors.

**Comment by waldekmastykarz** [comment]
What are the contents of your **config.json** file?

**Comment by Soumyawrk** [comment]
{
  "entries": [
    {
      "entry": "./lib/webparts/whetrWebpart/WhetrWebpartWebPart.js",
      "manifest": "./src/webparts/whetrWebpart/WhetrWebpartWebPart.manifest.json",
      "outputPath": "./dist/whetr-webpart.bundle.js"
    }
  ],
  "externals": {
    "@microsoft/sp-client-base": "node_modules/@microsoft/sp-client-base/dist/sp-client-base.js",
    "@microsoft/sp-client-preview": "node_modules/@microsoft/sp-client-preview/dist/sp-client-preview.js",
    "jquery":"node_modules/jquery/dist/jquery.min.js",
    "@microsoft/sp-lodash-subset": "node_modules/@microsoft/sp-lodash-subset/dist/sp-lodash-subset.js",
    "office-ui-fabric-react": "node_modules/office-ui-fabric-react/dist/office-ui-fabric-react.js",
    "react": "node_modules/react/dist/react.min.js",
    "react-dom": "node_modules/react-dom/dist/react-dom.min.js",
    "react-dom/server": "node_modules/react-dom/dist/react-dom-server.min.js",
    "simpleWeather": {
      "path": "https://cdnjs.cloudflare.com/ajax/libs/jquery.simpleWeather/3.1.0/jquery.simpleWeather.min.js",
      "globalName": "jQuery",
      "globalDependencies": [ "jquery" ]
    }
  },
  "localizedResources": {
    "whetrWebpartStrings": "webparts/whetrWebpart/loc/{locale}.js"
  }
}

**Comment by waldekmastykarz** [comment]
Your *externals* section should contain nothing else but the references to jQuery and simpleWeather. In the previous releases of the SharePoint Framework also the standards Microsoft packages have been listed in the *externals* section, but that's not the case with the latest release anymore.

**Comment by Soumyawrk** [comment]
Now my webpart is working fine in the local workbench but throwing some issue in dev site. I suppose there is some issue in authentication..
![issue in dev site](https://cloud.githubusercontent.com/assets/25977928/23646251/0b73bf86-0336-11e7-9cb6-20387c13e47e.PNG)

**Comment by joancloete** [comment]
Hi I am fairly new to the SPFX area and would like to package the weather web part and deploy it to my dev tenant. I cannot find a lot of information regarding the upgrade of an existing project to be RC1 ready, except [this one](https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-GA) on github. I am able to run it in the workbench, but once I package it and try to add it to a modern page I receive the following error message:

[SPWebPartErrorCode.ScriptLoadError]:: Unable to load web part WebPart.undefined.39d5c1b7-d7b5-4111-ad7f-1742eb3486df,Error: ***Failed to load component "de33e780-5ae0-4d1e-abbc-5ef3468debb1" (undefined). Original error: ***Failed to load entry point from component "de33e780-5ae0-4d1e-abbc-5ef3468debb1" (undefined). script resources due to: {1}. CALLSTACK:: Error at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-02-17.019/sp-loader_en-us_c7a5ee2faf8f15c3c9ab1ecc5e7db21d.js:57:21740) at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-02-17.019/sp-webpart-base_en-us_f7b0b90820799ba53083111c72956e29.js:47:22746) at Function.t.create (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-02-17.019/sp-webpart-base_en-us_f7b0b90820799ba53083111c72956e29.js:47:23187) at https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-02-17.019/sp-webpart-base_en-us_f7b0b90820799ba53083111c72956e29.js:48:6311


Changes I have made as per article referenced above are:
On the package.json file I have added new entries and update everything to 1.0.0

  "dependencies": {
    "@microsoft/sp-client-base": "~1.0.0",
    "@microsoft/sp-core-library": "~1.0.0",
    "@microsoft/sp-webpart-base": "~1.0.0"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.0.0",
    "@microsoft/sp-module-interfaces": "~1.0.0",
    "@microsoft/sp-webpart-workbench": "~1.0.0",
    "gulp": "~3.9.1"

Can you please advise?

Thank you!

**Comment by waldekmastykarz** [comment]
I've just updated the solution to SPFx GA. Feel free to compare it to your code and see what the differences are.

**Comment by joancloete** [comment]
Thank you very much, I have just been able to deploy it without errors! I will do the comparison later today :)

**Comment by waldekmastykarz** [comment]
Excellent! Great to hear it's working for you :)
